### ISSUE TITLE
Max Rows

### ISSUE THREAD

**Issue by gaston23** [buildo/react-autosize-textarea#25]
Hey,

It'd be awesome to have a "max-rows" prop. 

Thank you for your work.

**Comment by FrancescoCioria** [comment]
Hi @gaston23, thank you :)

in order to do that, `maxRows` will have to be translated into `max-height` somehow.

I made a quick POC (you can see the associated PR) but it's still a work-in-progress.
In the following days I'll see if I manage to complete it and if it works I say we can add this feature and release a new version

**Comment by gaston23** [comment]
@FrancescoCioria looks awesome! Thanks again, will keep subscribed to this.

**Comment by gaston23** [comment]
Thank you guys
