### ISSUE TITLE
Getting a lot of Null is not an object in production

### ISSUE THREAD

**Issue by r-tock** [buildo/react-autosize-textarea#27]
```
TypeError: null is not an object (evaluating 'n.textarea.dispatchEvent')
1
File "webpack:///./~/react-autosize-textarea/lib/TextareaAutosize.js" line 55 col 1 in a
return _this.textarea.dispatchEvent(event);
```

In Chrome 55 UI Webview , Mobile Safari UI Webview 10, Mobile iOS Webview 10.

All these are variants of the same iOS Safari 10 engine.

**Comment by r-tock** [comment]
Also seen are

```
TypeError: Cannot read property 'dispatchEvent' of null
1
File "webpack:///./~/react-autosize-textarea/lib/TextareaAutosize.js" line 55 col 1 in a
return _this.textarea.dispatchEvent(event);
```
This one only occurs in Chrome 55 on Windows

**Comment by FrancescoCioria** [comment]
Hi @r-tock , I'm sorry but I'm having trouble reproducing it.

What I can see from you logs is that the component is trying to dispatch an event through the ref `this.textarea` which, in your case, is `null`, and this generates the error.

Which version of `React` are you using? I'm asking because this looks like an error due to using an older version of `React` like `v0.13`

**Comment by r-tock** [comment]
we are on the latest react 15.4.1, these are caught by rollbar.js

**Comment by r-tock** [comment]
Is it possible that this is caused by some race condition? Maybe while the component is being unmounted.

**Comment by FrancescoCioria** [comment]
> Is it possible that this is caused by some race condition? Maybe while the component is being unmounted.

It's possible even if we're using it in production in several projects and it never happend to us 😕 

Still, I noticed that [this ugly `setTimeout`](prevProps) could be easily removed by using `componentDidUpdate` instead of `componentWillReceiveProps` to manually trigger un update!

I'm hoping that removing the async `setTimeout` will fix your problem.
