### ISSUE TITLE
How to detect keystrokes ?

### ISSUE THREAD

**Issue by EduardJS** [buildo/react-autosize-textarea#29]
Hello!

I was wondering how can I detect `e.which` for example inside `onChange`.
So far, it returns `undefined`.

Thanks

**Comment by FrancescoCioria** [comment]
Hi @EduardJS 

`e.which` is `undefined` because `ReactJS` uses a custom event object called [`SyntheticEvent`](https://facebook.github.io/react/docs/events.html) which in the case of the [`onChange`](https://facebook.github.io/react/docs/events.html#form-events) event, as you noted, doesn't have the property `e.which`.

If you need `e.which`, you must use a [keyboard event](https://facebook.github.io/react/docs/events.html#keyboard-events) such as `onKeyUp`.

PS: `e.which` [has been deprecated](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/which) by many browsers. I suggest you use `e.keyCode` instead :)

**Comment by EduardJS** [comment]
Ok! This small explanation just made me understand SyntheticEvent hehe.

Thanks!

**Comment by EduardJS** [comment]
One small question though ( on-topic ),

I am saving what is being pressed in `this.state.reply` for the `send` action which is triggered `onKeyDown` if `( e.which || e.keyCode ) == 13`, and my issue is.. how do I reset the component's `value` if I can't set `ref="reply"` nor bind the textarea's `value` to `this.state.value` ?

I've been looking at the source code, but it's not much I can gather.
I'm working on a chat app, and I'm trying to clean up the textarea when hitting send.

**Comment by FrancescoCioria** [comment]
The `TextareaAutosize` should always be in sync with `this.state.value`, so you can simply set `value` to `""` (or `null` or `undefined`) and it should be emptied right away:

```jsx
class MyComponent extends React.Component {
  
  state = {}

  onKeyDown = (e) => {
    if ((e.which || e.keyCode) === 13) {
      this.setState({ value: '' }); // React will automatically re-render "MyComponent" -> "TextareaAutosize" will receive the updated empty value
    }
  }

  onChange = ({ target: { value } }) => this.setState({ value }) // save user input in your component's state

  render() {
    return (
      <TextareaAutosize
        value={this.state.value}
        onChange={this.onChange}
        onKeyDown={this.onKeyDown}
      />
    );
  }

}
```

**Comment by EduardJS** [comment]
@FrancescoCioria Hmm, guess it's time I should look at why my `this.state.value` didn't function properly the last time.

Thanks for the great reply ( and for the example ).
Never knew `state` works like that. I mean, I knew I need to call `contructor` and `super` , then set `this.state` inside it.

Learning new stuff every day.

**Comment by gabro** [comment]
@EduardJS Just adding to @FrancescoCioria's reply: that syntax (`state = ...`) is a [ES proposal in stage 2](https://github.com/tc39/proposal-class-public-fields) which is not yet standard, although widely used.
You will need a babel transformation if you intend to use it.
