### ISSUE TITLE
How to hide the vertical scroll bar when maxRows is defined

### ISSUE THREAD

**Issue by cecton** [buildo/react-autosize-textarea#68]
## Long Story Short

I'm trying to hide the vertical scroll bar when the number of lines exceeds `maxRows`. For example I have `foo\nbar` in the textarea and `maxRows` is set to 1. To do so I pass `overflow: "hidden"` to the `style` attribute of the component. Apparently this attribute in particular is ignored. I tried also `overflowY: "hidden"` without success.

## Expected Behavior

The style attribute overrides also the `overflow*` attributes.

## Actual Behavior

The component ignores the specified `overflow*` style attributes.

## Use Case

I'm building a component that is a one-line field. When it gets focus, I want this component to expand to its full size. When I leave, I want this component to get back to one-line only **[edit] without a scroll bar**.

**Comment by cecton** [comment]
I just checked the code and apparently the overflow is handled by the lib autosize so I doubt there is a solution unless there is a parameter in autosize to override the scrollbar...

**Comment by FrancescoCioria** [comment]
Hi @cecton ,

> I'm building a component that is a one-line field. When it gets focus, I want this component to expand to its full size. When I leave, I want this component to get back to one-line only.

Can't you solve this by programmatically changing the prop "maxRows" from `1` to `undefined` when it gets focused and back to `1` when it gets blurred?

**Comment by cecton** [comment]
That's exactly what I do. When the maxRows is 1 the scroll bar appears.

**Comment by FrancescoCioria** [comment]
Ok I reproduced it, I'll look into the code, it's weird that it's ignoring `style={ overflow: 'hidden' }`

**Comment by FrancescoCioria** [comment]
So basically, as you already said, `overflow-x: hidden` and `overflow-y: scroll` are enforced by `autosize` which also removes any `overflow` style.

The problem here is that `overflow-y: scroll` is needed by `autosize` to work correctly so it would be too risky to mess with it...

The easiest solution for you would be to programmatically add a class `overflow-hidden-important` when you set `maxRows={1}` and then, in the CSS, set `.overflow-hidden-important { overflow: hidden !important }`.

**Comment by cecton** [comment]
Thanks! I think this will do the trick. Too bad there isn't a cleaner way...
